export * from './Accounts.entity';
export * from './Appointments.entity';
export * from './AppointmentTypes.entity';
export * from './Category.entity';
export * from './Credentials.entity';
// export * from './CustomerPayment.entity';
export * from './Customers.entity';
export * from './Doctors.entity';
export * from './ExaminationService.entity';
export * from './HealthFacilities.entity';
// export * from './HealthFacilitiesExaminationService.entity';
export * from './Payments.entity';
export * from './Permissions.entity';
export * from './Profiles.entity';
// export * from './RolePermission.entity';
export * from './Roles.entity';
export * from './ScheduleMeeting.entity';
export * from './Schedules.entity';
export * from './Specialties.entity';
export * from './TimeSlot.entity';